name: Continuous Integration Test

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      


    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Show GitHub Workspace
    - name: Print GITHUB_WORKSPACE
      run: echo ${GITHUB_WORKSPACE}

    # Run Continuous Integration
    - name: Continuous Integration Test
      run: |
        ./project/test.sh
              